export const API_DOMAIN = 'http://localhost:8443/';
export const DOMAIN = 'http://localhost:3000/';
// export const DOMAIN = 'https://xe.aceoffice.vn/';
// export const API_DOMAIN = 'https://fleet.aceoffice.vn/api/';
const API_MAP = {
    LOGIN: API_DOMAIN + 'auth/login',
    REFRESH_TOKEN: API_DOMAIN + 'auth/refresh-token',
    GET_USER_INFO: API_DOMAIN + 'user/get-user-info',
    OAUTH2_MICROSOFT: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize" +
        "?client_id=873e9530-8931-4ca7-98a1-a7c7415dae76" +
        "&response_type=token" +
        "&scope=openid profile email User.Read.All" +
        "&redirect_uri=" + API_DOMAIN + "callback/oauth2/microsoft/book"+
        "&prompt=login"+"" +
        "&state=12345",
    GET_LIST_USER: API_DOMAIN +"user/search",
    CHANGE_ACTIVE_USER:API_DOMAIN+"user/change-active",
    CHANGE_ACTIVE_ADVANCE:API_DOMAIN+"advance/change-active",
    GET_LIST_ROLE:API_DOMAIN+"role/search",
    CREATE_USER:API_DOMAIN+"user/create",
    UPDATE_USER:API_DOMAIN+"user/update",
    CREATE_ROLE:API_DOMAIN+"role/create",
    UPDATE_ROLE:API_DOMAIN+"role/update",
    DELETE_ROLE:API_DOMAIN+"role/delete",
    DELETE_USER:API_DOMAIN+"user/delete",
    CHANGE_USER:API_DOMAIN+"user/change-password",
    GET_LIST_PERMISSIONS:API_DOMAIN+"role/permission/get-all",
    GET_ROLE_PERMISSION:API_DOMAIN+"role/permission",
    SET_PERMISSION:API_DOMAIN+"role/set-permission",
    GET_LOGIN_HISTORY:API_DOMAIN+"login-history/search",
    LOGOUT_BY_ADMIN:API_DOMAIN+"login-history/logout-by-admin",
    GET_ORGANIZATION:API_DOMAIN+"organization/get-all",
    GET_ORGANIZATION_BY_USER:API_DOMAIN+"organization/get-by-user",
    GET_GROUP_EXPENSE:API_DOMAIN+"group-expense/get-all",
    GET_CONFIG_EMAIL:API_DOMAIN+"email/get-config-email",
    UPDATE_CONFIG_EMAIL:API_DOMAIN+"email/update",
    CHECK_CONFIG_EMAIL:API_DOMAIN+"email/check-config",
    CREATE_GROUP_EXPENSE:API_DOMAIN+"group-expense/create",
    UPDATE_GROUP_EXPENSE:API_DOMAIN+"group-expense/update",
    DELETE_GROUP_EXPENSE:API_DOMAIN+"group-expense/delete",
    GET_EXPENSE_GROUP_EXPENSE:API_DOMAIN+"group-expense/get-expense",
    CREATE_ORGANIZATION:API_DOMAIN+"organization/create",
    UPDATE_ORGANIZATION:API_DOMAIN+"organization/update",
    DELETE_ORGANIZATION:API_DOMAIN+"organization/delete",
    GET_EXPENSE_ORGANIZATION:API_DOMAIN+"organization/get-expense",
    GET_NOTIFICATION:API_DOMAIN+"notification/get",
    READ_NOTIFICATION:API_DOMAIN+"notification/read",


    DOWNLOAD_DOCUMENT:API_DOMAIN+"document/download-file",
    DOWNLOAD_DOCUMENT_NO_WATERMARK:API_DOMAIN+"document/download-file-no-watermark",
    GET_REPOSITORY_BY_ORGANIZATION:API_DOMAIN+"repository/get-by-organization",
    GET_REPOSITORY_BY_USER:API_DOMAIN+"public/repository/get-repository-book",
    GET_DETAIL_REPOSITORY:API_DOMAIN+"repository/get-detail",
    CREATE_REPOSITORY:API_DOMAIN+"repository/create",
    UPDATE_REPOSITORY:API_DOMAIN+"repository/update",
    DELETE_REPOSITORY:API_DOMAIN+"repository/delete",
    GET_CATEGORY:API_DOMAIN+"category/search",
    GET_PUBLISH_DOCUMENT_BY_ORGANIZATION:API_DOMAIN+"dashboard/get-publish-document-by-organization",
    GET_PUBLISH_DOCUMENT_BY_TIME:API_DOMAIN+"dashboard/get-publish-document-by-time",
    GET_DOSSIER_LOAN_BY_TIME:API_DOMAIN+"dashboard/get-dossier-loan-by-time",
    GET_PUBLISH_DOCUMENT_BY_MONTH:API_DOMAIN+"dashboard/get-publish-document-by-month",
    GET_PUBLISH_DOCUMENT_BY_TYPE_DOCUMENT:API_DOMAIN+"dashboard/get-publish-document-by-type-document",
    GET_DOSSIER_DASHBOARD_BY_GROUP_DOSSIER:API_DOMAIN+"dashboard/get-dossier-dashboard-by-group-dossier",
    GET_DOCUMENT_DASHBOARD_BY_TYPE_DOCUMENT:API_DOMAIN+"dashboard/get-document-dashboard-by-type-document",
    GET_LATE_DOSSIER_LOAN:API_DOMAIN+"dashboard/get-late-dossier-loan",
    CREATE_CATEGORY:API_DOMAIN+"category/create",
    UPDATE_CATEGORY:API_DOMAIN+"category/update",
    DELETE_CATEGORY:API_DOMAIN+"category/delete",
    GET_DOSSIER:API_DOMAIN+"dossier/search",
    GET_DOSSIER_IN_ORGANIZATION:API_DOMAIN+"dossier/search-in-organization",
    SEARCH_DOSSIER_LOAN:API_DOMAIN+"dossier/search-dossier-loan",
    GET_DETAIL_DOSSIER:API_DOMAIN+"dossier/get-detail",
    CREATE_DOSSIER:API_DOMAIN+"dossier/create",
    UPDATE_DOSSIER:API_DOMAIN+"dossier/update",
    DELETE_DOSSIER:API_DOMAIN+"dossier/delete",
    SHARE_DOSSIER:API_DOMAIN+"dossier/share",
    REMOVE_SHARE_DOSSIER:API_DOMAIN+"dossier/remove-share",
    TRANSFER_DOSSIER:API_DOMAIN+"dossier/transfer",
    CANCEL_DOSSIER:API_DOMAIN+"dossier/cancel-transfer",
    ACCEPT_DOSSIER:API_DOMAIN+"dossier/accept-transfer",
    REJECT_DOSSIER:API_DOMAIN+"dossier/reject-transfer",
    SEARCH_TRANSFER_DOSSIER:API_DOMAIN+"dossier/transfer/search",
    SEARCH_TRANSFER_DOCUMENT:API_DOMAIN+"document/transfer/search",

    GET_CONFIG_TABLE:API_DOMAIN+"table-config/get",
    UPDATE_CONFIG_TABLE:API_DOMAIN+"table-config/update",
    DEFAULT_CONFIG_TABLE:API_DOMAIN+"table-config/create-default",

    GET_DOCUMENT:API_DOMAIN+"document/search",
    GET_DOCUMENT_ORGANIZATION:API_DOMAIN+"document/search-in-organization",
    GET_DETAIL_DOCUMENT:API_DOMAIN+"document/get-detail",
    CREATE_DOCUMENT:API_DOMAIN+"document/create",
    UPDATE_DOCUMENT:API_DOMAIN+"document/update",
    DELETE_DOCUMENT:API_DOMAIN+"document/delete",
    SHARE_DOCUMENT:API_DOMAIN+"document/share",
    UPDATE_SHARE_DOCUMENT:API_DOMAIN+"document/share/update",
    REMOVE_SHARE_DOCUMENT:API_DOMAIN+"document/share/remove",
    TRANSFER_DOCUMENT:API_DOMAIN+"document/transfer",
    CANCEL_DOCUMENT:API_DOMAIN+"document/cancel-transfer",
    ACCEPT_DOCUMENT:API_DOMAIN+"document/accept-transfer",
    REJECT_DOCUMENT:API_DOMAIN+"document/reject-transfer",
    GET_PUBLISH_DOCUMENT:API_DOMAIN+"publish-document/search",
    GET_PUBLISH_DOCUMENT_MANAGE:API_DOMAIN+"publish-document/search-manage",
    SEND_PUBLISH_DOCUMENT:API_DOMAIN+"publish-document/send",
    UPDATE_PUBLISH_DOCUMENT:API_DOMAIN+"publish-document/update",
    CANCEL_PUBLISH_DOCUMENT:API_DOMAIN+"publish-document/cancel",
    DELETE_PUBLISH_DOCUMENT:API_DOMAIN+"publish-document/delete",
    GET_SHARE_DOCUMENT:API_DOMAIN+"document/share/search",
    LOAN_DOSSIER:API_DOMAIN+"dossier/loan",
    LOAN_DOSSIER_SEARCH:API_DOMAIN+"dossier/loan/search",
    CANCEL_LOAN_DOSSIER:API_DOMAIN+"dossier/loan/cancel",
    REJECT_LOAN_DOSSIER:API_DOMAIN+"dossier/loan/reject",
    ACCEPT_LOAN_DOSSIER:API_DOMAIN+"dossier/loan/accept",
    REQUEST_RETURN_HARD_COPY:API_DOMAIN+"dossier/loan/request-return-hard-copy",
    ACCEPT_RETURN_HARD_COPY:API_DOMAIN+"dossier/loan/accept-return-hard-copy",

    //book
    LOAN_BOOK:API_DOMAIN+"book/loan",
    LOAN_BOOK_SEARCH:API_DOMAIN+"public/loan/search",
    CANCEL_LOAN_BOOK:API_DOMAIN+"book/loan/cancel",
    REJECT_LOAN_BOOK:API_DOMAIN+"book/loan/reject",
    ACCEPT_LOAN_BOOK:API_DOMAIN+"book/loan/accept",
    REQUEST_RETURN_BOOK:API_DOMAIN+"book/loan/request-return",
    ACCEPT_RETURN_BOOK:API_DOMAIN+"book/loan/accept-return",

    GET_LIST_BOOK:API_DOMAIN+"public/book/search",
    CREATE_BOOK:API_DOMAIN+"book/create",
    UPDATE_BOOK:API_DOMAIN+"book/update",
    DELETE_BOOK:API_DOMAIN+"book/delete",
    DOWNLOAD_THUMBNAIL_BOOK:API_DOMAIN+"car/download-file",
    DOWNLOAD_BOOK_PDF:API_DOMAIN+"book/download-file",

    GET_LIST_BOOK_INTRODUCTION:API_DOMAIN+"public/book-introduction/search",
    READ_BOOK_INTRODUCTION:API_DOMAIN+"public/book-introduction/read",


    BOSS_SEARCH:API_DOMAIN+"boss/search",
    BOSS_CREATE:API_DOMAIN+"boss/create",
    BOSS_UPDATE:API_DOMAIN+"boss/update",
    BOSS_DELETE:API_DOMAIN+"boss/delete",

    CRASH_REPORT_SEARCH:API_DOMAIN+"driver/crash-report/search",
    CRASH_REPORT_CREATE:API_DOMAIN+"driver/crash-report/create",
    CRASH_REPORT_UPDATE:API_DOMAIN+"driver/crash-report/update",
    CRASH_REPORT_DELETE:API_DOMAIN+"driver/crash-report/delete",

    MAINTENANCE_SEARCH:API_DOMAIN+"maintenance/search",
    MAINTENANCE_CREATE:API_DOMAIN+"maintenance/create",
    MAINTENANCE_UPDATE:API_DOMAIN+"maintenance/update",
    MAINTENANCE_DELETE:API_DOMAIN+"maintenance/delete",

    CHECKLIST_CAR_SEARCH:API_DOMAIN+"checklist-car/search",
    CHECKLIST_CAR_CREATE:API_DOMAIN+"checklist-car/create",
    CHECKLIST_CAR_UPDATE:API_DOMAIN+"checklist-car/update",
    CHECKLIST_CAR_DELETE:API_DOMAIN+"checklist-car/delete",

    SCHEDULE_TEMPLATE_SEARCH:API_DOMAIN+"schedule-template/search",
    SCHEDULE_TEMPLATE_CREATE:API_DOMAIN+"schedule-template/create",
    SCHEDULE_TEMPLATE_UPDATE:API_DOMAIN+"schedule-template/update",
    SCHEDULE_TEMPLATE_DELETE:API_DOMAIN+"schedule-template/delete",

    HISTORY_TRANSFER_SEARCH:API_DOMAIN+"history-transfer/search",
    HISTORY_TRANSFER_CREATE:API_DOMAIN+"history-transfer/create",
    HISTORY_TRANSFER_UPDATE:API_DOMAIN+"history-transfer/update",
    HISTORY_TRANSFER_DELETE:API_DOMAIN+"history-transfer/delete",
    HISTORY_TRANSFER_DOWNLOAD:API_DOMAIN+"history-transfer/download-file",

    EXPENSE_SEARCH:API_DOMAIN+"driver/expense/search",
    EXPENSE_CREATE:API_DOMAIN+"driver/expense/create",
    EXPENSE_UPDATE:API_DOMAIN+"driver/expense/update",
    EXPENSE_DELETE:API_DOMAIN+"driver/expense/delete",

    CAR_SEARCH:API_DOMAIN+"car/search",
    CAR_CREATE:API_DOMAIN+"car/create",
    CAR_UPDATE:API_DOMAIN+"car/update",
    CAR_DELETE:API_DOMAIN+"car/delete",
    CAR_DOWNLOAD:API_DOMAIN+"car/download-file",

    SCHEDULE_SEARCH:API_DOMAIN+"schedule/search",
    SCHEDULE_GET:API_DOMAIN+"schedule/get",
    SCHEDULE_GET_DETAIL:API_DOMAIN+"schedule/detail",
    SCHEDULE_CREATE:API_DOMAIN+"schedule/create",
    SCHEDULE_UPDATE:API_DOMAIN+"schedule/update",
    SCHEDULE_UPDATE_STATUS:API_DOMAIN+"schedule/update-status",
    SCHEDULE_DELETE:API_DOMAIN+"schedule/delete",
}
export default API_MAP;
